# POSTGRES LOCAL / DEFAULT DATASOURCE (fallback)
spring.datasource.url=jdbc:postgresql://localhost:5432/gerador_excedente
spring.datasource.username=postgres
spring.datasource.password=20058868662006123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT BASE (usado localmente, mas ao subir deploy o valor armazenado na váriavel estará no render)
jwt.secret=minha-chave-super-secreta-para-jwt-2026-projeto-excedente
jwt.expiration=3600000
jwt.refresh-expiration=604800000

# Para debug de JPA
spring.jpa.properties.hibernate.format_sql=true


# ==========================================================
# ATIVA OPEN-IN-VIEW
# Permite que a sessão do Hibernate permaneça aberta
# durante toda a requisição HTTP.
#
# Isso possibilita acessar entidades LAZY fora da camada
# de serviço (ex: na camada de controller ou view).
#
# Atenção:
# Pode causar consultas adicionais ao banco fora da
# transação principal e impactar performance.
# ==========================================================
spring.jpa.open-in-view=true


# =====================================================
# 🍪 CONFIGURAÇÃO DE COOKIES - DESENVOLVIMENTO
# =====================================================
#
# Ambiente local (localhost)
#
# SameSite=Strict:
# - Cookie enviado apenas para o mesmo site.
# - Maior proteção contra CSRF.
# - Ideal para desenvolvimento local.
#
# Secure=false:
# - Permite funcionamento em HTTP.
# - Necessário para localhost sem HTTPS.
#
# ⚠️ IMPORTANTE:
# Não utilizar estas configurações em produção.
#
# =====================================================

app.cookie.same-site=Strict
app.cookie.secure=false